/* ============================================================
   KITHRA — curated book catalog (100+ titles)
   Public-domain titles include `read` (full text in /books) so they
   can be read in-app. Copyrighted titles show a summary + key ideas
   and link out to borrow/buy (no copyrighted full text is bundled).
   ============================================================ */
const CATS = ['Sales & Persuasion','Negotiation','Communication','Psychology & Influence','Leadership','Habits & Productivity','Mindfulness & Wellbeing','Relationships','Public Speaking','Strategy & Philosophy','Money & Business'];

const KITHRA_BOOKS = [
  // ---------- Sales & Persuasion ----------
  { id:'spin-selling', title:'SPIN Selling', author:'Neil Rackham', cat:'Sales & Persuasion', year:1988, summary:'Research-backed questioning method for complex B2B sales.', ideas:['Situation, Problem, Implication, Need-payoff questions','Build the buyer’s own case for change','Closing tactics hurt large sales'] },
  { id:'challenger-sale', title:'The Challenger Sale', author:'Matthew Dixon & Brent Adamson', cat:'Sales & Persuasion', year:2011, summary:'Top reps teach, tailor, and take control rather than just build rapport.', ideas:['Teach customers something new','Tailor to the stakeholder','Take control of the conversation'] },
  { id:'to-sell-is-human', title:'To Sell Is Human', author:'Daniel H. Pink', cat:'Sales & Persuasion', year:2012, summary:'Everyone is in sales now; modern persuasion is about attunement and service.', ideas:['Attunement, buoyancy, clarity','Serve, don’t just sell','Reframe problems for buyers'] },
  { id:'little-red-book-selling', title:'Little Red Book of Selling', author:'Jeffrey Gitomer', cat:'Sales & Persuasion', year:2004, summary:'Punchy principles on why people buy and how to earn loyalty.', ideas:['People buy for their reasons','Value first, price later','Earn referrals through service'] },
  { id:'new-strategic-selling', title:'The New Strategic Selling', author:'Robert Miller & Stephen Heiman', cat:'Sales & Persuasion', year:1985, summary:'Map every buying influence to win complex deals.', ideas:['Economic, user, technical buyers','Find your coach','Win-win or no deal'] },
  { id:'gap-selling', title:'Gap Selling', author:'Keenan', cat:'Sales & Persuasion', year:2018, summary:'Sell the gap between the customer’s current and desired state.', ideas:['Diagnose before prescribing','Quantify the cost of the problem','Outcomes over features'] },
  { id:'pitch-anything', title:'Pitch Anything', author:'Oren Klaff', cat:'Sales & Persuasion', year:2011, summary:'Frame control and status are what actually move a pitch.', ideas:['Win the frame','Create intrigue and stakes','Avoid neediness'] },
  { id:'the-psychology-of-selling', title:'The Psychology of Selling', author:'Brian Tracy', cat:'Sales & Persuasion', year:2004, summary:'Mindset and fundamentals that separate top earners.', ideas:['Self-concept drives results','Build trust early','Ask for the order'] },
  { id:'sell-with-a-story', title:'Sell with a Story', author:'Paul Smith', cat:'Sales & Persuasion', year:2016, summary:'Stories make your message stick and persuade.', ideas:['Hook, context, struggle, resolution','Make the buyer the hero','Practice your stories'] },

  // ---------- Negotiation ----------
  { id:'never-split-the-difference', title:'Never Split the Difference', author:'Chris Voss', cat:'Negotiation', year:2016, summary:'An FBI hostage negotiator’s playbook for everyday deals.', ideas:['Tactical empathy & labeling','Calibrated “how/what” questions','Aim for “that’s right”'] },
  { id:'getting-to-yes', title:'Getting to Yes', author:'Roger Fisher & William Ury', cat:'Negotiation', year:1981, summary:'Principled negotiation: separate people from the problem.', ideas:['Interests, not positions','Invent options for mutual gain','Use objective criteria'] },
  { id:'getting-past-no', title:'Getting Past No', author:'William Ury', cat:'Negotiation', year:1991, summary:'How to negotiate with difficult people and reach agreement.', ideas:['Go to the balcony','Step to their side','Build them a golden bridge'] },
  { id:'bargaining-for-advantage', title:'Bargaining for Advantage', author:'G. Richard Shell', cat:'Negotiation', year:1999, summary:'Negotiation strategy matched to your personality and situation.', ideas:['Know your style','Set high but justifiable goals','Leverage and standards'] },
  { id:'influence-without-authority', title:'Influence Without Authority', author:'Allan Cohen & David Bradford', cat:'Negotiation', year:1989, summary:'Get things done across an organization without formal power.', ideas:['Law of reciprocity','Trade “currencies”','Map stakeholders'] },
  { id:'difficult-conversations', title:'Difficult Conversations', author:'Stone, Patton & Heen', cat:'Negotiation', year:1999, summary:'Handle high-stakes conversations from the Harvard Negotiation Project.', ideas:['The “three conversations”','Move from blame to contribution','Manage identity and feelings'] },
  { id:'crucial-conversations', title:'Crucial Conversations', author:'Patterson, Grenny, McMillan & Switzler', cat:'Negotiation', year:2002, summary:'Tools for talking when stakes are high and emotions run strong.', ideas:['Make it safe','Master your stories','Share facts, then conclusions'] },

  // ---------- Communication ----------
  { id:'nonviolent-communication', title:'Nonviolent Communication', author:'Marshall B. Rosenberg', cat:'Communication', year:1999, summary:'A language of compassion: observe, feel, need, request.', ideas:['Separate observation from evaluation','Name feelings and needs','Make clear requests'] },
  { id:'how-to-win-friends', title:'How to Win Friends and Influence People', author:'Dale Carnegie', cat:'Communication', year:1936, summary:'The classic on dealing with people and earning genuine influence.', ideas:['Make others feel important','Show genuine interest','Win cooperation, not arguments'] },
  { id:'just-listen', title:'Just Listen', author:'Mark Goulston', cat:'Communication', year:2009, summary:'A psychiatrist’s techniques to truly get through to anyone.', ideas:['Move people from resisting to listening','Feel felt','The magic of empathy'] },
  { id:'words-that-work', title:'Words That Work', author:'Frank Luntz', cat:'Communication', year:2007, summary:'It’s not what you say, it’s what people hear.', ideas:['Simplicity and credibility','Frame for the listener','Words have weight'] },
  { id:'made-to-stick', title:'Made to Stick', author:'Chip & Dan Heath', cat:'Communication', year:2007, summary:'Why some ideas survive and others die — and how to make yours stick.', ideas:['Simple, Unexpected, Concrete','Credible, Emotional, Stories (SUCCESs)','Beat the curse of knowledge'] },
  { id:'talk-like-ted', title:'Talk Like TED', author:'Carmine Gallo', cat:'Communication', year:2014, summary:'Nine public-speaking secrets of the world’s top minds.', ideas:['Emotion, novelty, memorability','Tell stories','Keep it under 18 minutes'] },
  { id:'thanks-for-the-feedback', title:'Thanks for the Feedback', author:'Douglas Stone & Sheila Heen', cat:'Communication', year:2014, summary:'The science and art of receiving feedback well.', ideas:['Appreciation, coaching, evaluation','Spot your triggers','Find the 5% that’s useful'] },
  { id:'the-prophet', title:'The Prophet', author:'Kahlil Gibran', cat:'Communication', year:1923, summary:'Poetic essays on love, work, and speaking from the heart.', ideas:['Speak with intention','On giving and receiving','Timeless reflections'], read:'books/the-prophet.txt', pd:true },

  // ---------- Psychology & Influence ----------
  { id:'influence', title:'Influence: The Psychology of Persuasion', author:'Robert Cialdini', cat:'Psychology & Influence', year:1984, summary:'The six universal principles that drive people to say yes.', ideas:['Reciprocity, commitment, social proof','Authority, liking, scarcity','Defend against manipulation'] },
  { id:'pre-suasion', title:'Pre-Suasion', author:'Robert Cialdini', cat:'Psychology & Influence', year:2016, summary:'The moment before your message decides whether it lands.', ideas:['Channel attention first','Privileged moments','Set the stage'] },
  { id:'thinking-fast-and-slow', title:'Thinking, Fast and Slow', author:'Daniel Kahneman', cat:'Psychology & Influence', year:2011, summary:'Two systems of thought and the biases that shape decisions.', ideas:['System 1 vs System 2','Anchoring and framing','Loss aversion'] },
  { id:'predictably-irrational', title:'Predictably Irrational', author:'Dan Ariely', cat:'Psychology & Influence', year:2008, summary:'The hidden, systematic forces that shape our choices.', ideas:['The power of free','Relativity in decisions','The cost of social norms'] },
  { id:'the-catalyst', title:'The Catalyst: How to Change Anyone’s Mind', author:'Jonah Berger', cat:'Psychology & Influence', year:2020, summary:'Remove barriers instead of pushing harder.', ideas:['Reduce reactance','Ease endowment & distance','Lower uncertainty'] },
  { id:'drive', title:'Drive', author:'Daniel H. Pink', cat:'Psychology & Influence', year:2009, summary:'What truly motivates us: autonomy, mastery, purpose.', ideas:['Intrinsic > extrinsic','Autonomy fuels engagement','Purpose matters'] },
  { id:'mindset', title:'Mindset', author:'Carol Dweck', cat:'Psychology & Influence', year:2006, summary:'Fixed vs growth mindset and how beliefs shape success.', ideas:['Growth mindset','Effort over talent','Embrace challenges'] },
  { id:'meditations', title:'Meditations', author:'Marcus Aurelius', cat:'Psychology & Influence', year:180, summary:'A Roman emperor’s private Stoic notes on self-mastery.', ideas:['Control your judgments','Memento mori','Virtue is enough'], read:'books/meditations.txt', pd:true },

  // ---------- Leadership ----------
  { id:'start-with-why', title:'Start with Why', author:'Simon Sinek', cat:'Leadership', year:2009, summary:'Great leaders inspire by starting with purpose.', ideas:['The Golden Circle','People buy the why','Clarity, discipline, consistency'] },
  { id:'leaders-eat-last', title:'Leaders Eat Last', author:'Simon Sinek', cat:'Leadership', year:2014, summary:'Why some teams pull together and others don’t.', ideas:['Circle of safety','Trust and biology','Servant leadership'] },
  { id:'dare-to-lead', title:'Dare to Lead', author:'Brené Brown', cat:'Leadership', year:2018, summary:'Brave, values-led leadership built on vulnerability.', ideas:['Rumble with vulnerability','Clear is kind','Live your values'] },
  { id:'the-five-dysfunctions', title:'The Five Dysfunctions of a Team', author:'Patrick Lencioni', cat:'Leadership', year:2002, summary:'A leadership fable on what makes teams fail or thrive.', ideas:['Trust is the base','Embrace healthy conflict','Accountability and results'] },
  { id:'radical-candor', title:'Radical Candor', author:'Kim Scott', cat:'Leadership', year:2017, summary:'Care personally and challenge directly.', ideas:['Care personally + challenge directly','Avoid ruinous empathy','Guidance, team, results'] },
  { id:'extreme-ownership', title:'Extreme Ownership', author:'Jocko Willink & Leif Babin', cat:'Leadership', year:2015, summary:'Navy SEAL principles of total responsibility.', ideas:['Own everything','Keep it simple','Prioritize and execute'] },
  { id:'good-to-great', title:'Good to Great', author:'Jim Collins', cat:'Leadership', year:2001, summary:'Why some companies make the leap and others don’t.', ideas:['Level 5 leadership','First who, then what','The Hedgehog Concept'] },
  { id:'the-art-of-war', title:'The Art of War', author:'Sun Tzu', cat:'Leadership', year:-500, summary:'Ancient strategy on winning through preparation and positioning.', ideas:['Win before you fight','Know yourself and the other','Adapt to terrain'], read:'books/art-of-war.txt', pd:true },
  { id:'the-prince', title:'The Prince', author:'Niccolò Machiavelli', cat:'Leadership', year:1532, summary:'A frank, controversial classic on power and leadership.', ideas:['Pragmatism over idealism','Reputation and perception','Adapt to fortune'], read:'books/the-prince.txt', pd:true },
  { id:'autobiography-franklin', title:'The Autobiography of Benjamin Franklin', author:'Benjamin Franklin', cat:'Leadership', year:1791, summary:'Self-improvement and character from a founding polymath.', ideas:['13 virtues','Habits of industry','Lifelong learning'], read:'books/autobiography-of-benjamin-franklin.txt', pd:true },

  // ---------- Habits & Productivity ----------
  { id:'atomic-habits', title:'Atomic Habits', author:'James Clear', cat:'Habits & Productivity', year:2018, summary:'Tiny changes, remarkable results — the mechanics of habit.', ideas:['1% better every day','Make it obvious/easy/attractive/satisfying','Systems over goals'] },
  { id:'the-power-of-habit', title:'The Power of Habit', author:'Charles Duhigg', cat:'Habits & Productivity', year:2012, summary:'How habits work and how to change them.', ideas:['Cue, routine, reward','Keystone habits','Belief drives change'] },
  { id:'deep-work', title:'Deep Work', author:'Cal Newport', cat:'Habits & Productivity', year:2016, summary:'Focused success in a distracted world.', ideas:['Protect deep focus','Embrace boredom','Quit shallow work'] },
  { id:'getting-things-done', title:'Getting Things Done', author:'David Allen', cat:'Habits & Productivity', year:2001, summary:'Stress-free productivity by capturing everything.', ideas:['Capture, clarify, organize','Two-minute rule','Mind like water'] },
  { id:'essentialism', title:'Essentialism', author:'Greg McKeown', cat:'Habits & Productivity', year:2014, summary:'The disciplined pursuit of less but better.', ideas:['Less but better','Trade-offs are real','Protect the vital few'] },
  { id:'the-7-habits', title:'The 7 Habits of Highly Effective People', author:'Stephen R. Covey', cat:'Habits & Productivity', year:1989, summary:'Principle-centered effectiveness, personal and interpersonal.', ideas:['Be proactive','Begin with the end in mind','Seek first to understand'] },
  { id:'how-to-live-on-24-hours', title:'How to Live on 24 Hours a Day', author:'Arnold Bennett', cat:'Habits & Productivity', year:1908, summary:'A timeless little book on using your time well.', ideas:['Time is the great equalizer','Guard your evenings','Live deliberately'], read:'books/how-to-live-on-24-hours-a-day.txt', pd:true },
  { id:'as-a-man-thinketh', title:'As a Man Thinketh', author:'James Allen', cat:'Habits & Productivity', year:1903, summary:'A short classic: your thoughts shape your character and life.', ideas:['Thought becomes action','Mind is the master','Calmness is power'], read:'books/as-a-man-thinketh.txt', pd:true },

  // ---------- Mindfulness & Wellbeing ----------
  { id:'wherever-you-go', title:'Wherever You Go, There You Are', author:'Jon Kabat-Zinn', cat:'Mindfulness & Wellbeing', year:1994, summary:'An accessible guide to mindfulness in everyday life.', ideas:['Present-moment awareness','Non-judging attention','Practice, don’t perform'] },
  { id:'the-power-of-now', title:'The Power of Now', author:'Eckhart Tolle', cat:'Mindfulness & Wellbeing', year:1997, summary:'Finding peace by living fully in the present.', ideas:['You are not your mind','Watch the thinker','Surrender to now'] },
  { id:'why-we-sleep', title:'Why We Sleep', author:'Matthew Walker', cat:'Mindfulness & Wellbeing', year:2017, summary:'The new science of sleep and why it matters.', ideas:['Sleep is non-negotiable','REM and memory','Protect your circadian rhythm'] },
  { id:'the-body-keeps-the-score', title:'The Body Keeps the Score', author:'Bessel van der Kolk', cat:'Mindfulness & Wellbeing', year:2014, summary:'How trauma reshapes body and brain, and paths to heal.', ideas:['Trauma lives in the body','Safety and regulation','Many roads to recovery'] },
  { id:'mans-search-for-meaning', title:'Man’s Search for Meaning', author:'Viktor E. Frankl', cat:'Mindfulness & Wellbeing', year:1946, summary:'Finding purpose even in suffering, from a Holocaust survivor.', ideas:['Meaning over pleasure','Choose your response','The “why” to bear any how'] },
  { id:'tao-te-ching', title:'Tao Te Ching', author:'Lao Tzu', cat:'Mindfulness & Wellbeing', year:-400, summary:'Foundational Taoist verses on simplicity and flow.', ideas:['Wu wei (effortless action)','Yield to overcome','Less is more'], read:'books/tao-te-ching.txt', pd:true },
  { id:'walden', title:'Walden', author:'Henry David Thoreau', cat:'Mindfulness & Wellbeing', year:1854, summary:'Reflections on simple, deliberate living in nature.', ideas:['Simplify, simplify','Live deliberately','Wealth is inner'], read:'books/walden.txt', pd:true },

  // ---------- Relationships ----------
  { id:'the-five-love-languages', title:'The 5 Love Languages', author:'Gary Chapman', cat:'Relationships', year:1992, summary:'How people give and receive love differently.', ideas:['Words, time, gifts, service, touch','Speak their language','Fill the love tank'] },
  { id:'attached', title:'Attached', author:'Amir Levine & Rachel Heller', cat:'Relationships', year:2010, summary:'Attachment science for healthier adult relationships.', ideas:['Secure, anxious, avoidant','Know your pattern','Choose secure partners'] },
  { id:'hold-me-tight', title:'Hold Me Tight', author:'Dr. Sue Johnson', cat:'Relationships', year:2008, summary:'Seven conversations for a lifetime of love (EFT).', ideas:['Recognize demon dialogues','Reach for your partner','Emotional responsiveness'] },
  { id:'the-seven-principles', title:'The Seven Principles for Making Marriage Work', author:'John Gottman', cat:'Relationships', year:1999, summary:'Research-based habits of couples that last.', ideas:['Build love maps','Turn toward bids','Manage conflict gently'] },
  { id:'models', title:'Models', author:'Mark Manson', cat:'Relationships', year:2011, summary:'Attraction through honesty and vulnerability.', ideas:['Be vulnerable','Non-neediness','Honesty over tactics'] },
  { id:'the-road-less-traveled', title:'The Road Less Traveled', author:'M. Scott Peck', cat:'Relationships', year:1978, summary:'Discipline, love, and growth toward maturity.', ideas:['Life is difficult','Love is an action','Discipline and grace'] },

  // ---------- Public Speaking ----------
  { id:'art-of-public-speaking', title:'The Art of Public Speaking', author:'Dale Carnegie & J.B. Esenwein', cat:'Public Speaking', year:1915, summary:'The original, thorough manual on speaking with confidence.', ideas:['Earn confidence through practice','Voice, pause, emphasis','Connect with the audience'], read:'books/art-of-public-speaking.txt', pd:true },
  { id:'ted-talks', title:'TED Talks: The Official TED Guide', author:'Chris Anderson', cat:'Public Speaking', year:2016, summary:'How to give talks that resonate, from TED’s curator.', ideas:['Build one idea','Connection first','Through-line and narration'] },
  { id:'confessions-public-speaker', title:'Confessions of a Public Speaker', author:'Scott Berkun', cat:'Public Speaking', year:2009, summary:'Honest, practical lessons from a pro speaker.', ideas:['Practice out loud','Manage fear','Design for attention'] },
  { id:'speak-with-no-fear', title:'Speak With No Fear', author:'Mike Acker', cat:'Public Speaking', year:2019, summary:'Strategies to overcome speaking anxiety fast.', ideas:['Prepare to lower fear','Reframe nerves','Practice systematically'] },

  // ---------- Strategy & Philosophy ----------
  { id:'the-republic', title:'The Republic', author:'Plato', cat:'Strategy & Philosophy', year:-380, summary:'A foundational dialogue on justice, society, and the good life.', ideas:['Justice in soul and city','The cave allegory','Philosopher rulers'], read:'books/the-republic.txt', pd:true },
  { id:'self-reliance', title:'Self-Reliance & Other Essays', author:'Ralph Waldo Emerson', cat:'Strategy & Philosophy', year:1841, summary:'Emerson’s essays on individuality and trusting yourself.', ideas:['Trust thyself','Nonconformity','Inner authority'], read:'books/self-reliance.txt', pd:true },
  { id:'aesops-fables', title:'Aesop’s Fables', author:'Aesop', cat:'Strategy & Philosophy', year:-560, summary:'Timeless short fables with moral lessons.', ideas:['Wisdom in stories','Character and consequence','Memorable morals'], read:'books/aesops-fables.txt', pd:true },
  { id:'the-obstacle-is-the-way', title:'The Obstacle Is the Way', author:'Ryan Holiday', cat:'Strategy & Philosophy', year:2014, summary:'Turning trials into triumph with Stoic practice.', ideas:['Perception, action, will','Obstacles become the path','Control what you can'] },
  { id:'antifragile', title:'Antifragile', author:'Nassim Nicholas Taleb', cat:'Strategy & Philosophy', year:2012, summary:'Things that gain from disorder.', ideas:['Beyond resilience','Optionality','Skin in the game'] },
  { id:'range', title:'Range', author:'David Epstein', cat:'Strategy & Philosophy', year:2019, summary:'Why generalists triumph in a specialized world.', ideas:['Sampling period','Slow learning sticks','Analogical thinking'] },
  { id:'the-almanack-naval', title:'The Almanack of Naval Ravikant', author:'Eric Jorgenson', cat:'Strategy & Philosophy', year:2020, summary:'Naval’s wisdom on wealth and happiness.', ideas:['Build specific knowledge','Play long-term games','Happiness is a skill'] },

  // ---------- Money & Business ----------
  { id:'the-art-of-money-getting', title:'The Art of Money Getting', author:'P. T. Barnum', cat:'Money & Business', year:1880, summary:'Barnum’s witty rules for making and keeping money.', ideas:['Avoid debt','Persevere','Use the right vocation'], read:'books/the-art-of-money-getting.txt', pd:true },
  { id:'rich-dad-poor-dad', title:'Rich Dad Poor Dad', author:'Robert Kiyosaki', cat:'Money & Business', year:1997, summary:'Mindset shifts about money, assets, and freedom.', ideas:['Assets vs liabilities','Make money work for you','Financial literacy'] },
  { id:'psychology-of-money', title:'The Psychology of Money', author:'Morgan Housel', cat:'Money & Business', year:2020, summary:'Timeless lessons on wealth, greed, and happiness.', ideas:['Behavior > math','Room for error','Enough'] },
  { id:'the-lean-startup', title:'The Lean Startup', author:'Eric Ries', cat:'Money & Business', year:2011, summary:'Build-measure-learn for startups under uncertainty.', ideas:['MVP','Validated learning','Pivot or persevere'] },
  { id:'zero-to-one', title:'Zero to One', author:'Peter Thiel', cat:'Money & Business', year:2014, summary:'Notes on startups and building the future.', ideas:['Go from 0 to 1','Monopoly via differentiation','Secrets worth pursuing'] },
  { id:'the-mom-test', title:'The Mom Test', author:'Rob Fitzpatrick', cat:'Money & Business', year:2013, summary:'How to talk to customers and get the truth.', ideas:['Ask about their life','Avoid pitching','Talk specifics, not opinions'] },
  { id:'hooked', title:'Hooked', author:'Nir Eyal', cat:'Money & Business', year:2014, summary:'How to build habit-forming products, ethically.', ideas:['Trigger, action, reward, investment','Variable rewards','Build for good habits'] },
  { id:'crossing-the-chasm', title:'Crossing the Chasm', author:'Geoffrey Moore', cat:'Money & Business', year:1991, summary:'Marketing tech products to mainstream customers.', ideas:['Early vs mainstream','Target a beachhead','Whole-product thinking'] },
  { id:'good-strategy-bad-strategy', title:'Good Strategy Bad Strategy', author:'Richard Rumelt', cat:'Money & Business', year:2011, summary:'What real strategy is — and the fluff that isn’t.', ideas:['Diagnosis, policy, action','Focus power on a pivot','Avoid “dog’s dinner” goals'] },

  // ---------- More essentials ----------
  { id:'fanatical-prospecting', title:'Fanatical Prospecting', author:'Jeb Blount', cat:'Sales & Persuasion', year:2015, summary:'Keep the pipeline full with relentless, balanced prospecting.', ideas:['The 30-day rule','Balance your prospecting','Own the phone'] },
  { id:'snap-selling', title:'SNAP Selling', author:'Jill Konrath', cat:'Sales & Persuasion', year:2010, summary:'Win over frazzled, time-crunched buyers.', ideas:['Simple, iNvaluable, Aligned, Priority','Respect their time','Be a resource'] },
  { id:'start-with-no', title:'Start with No', author:'Jim Camp', cat:'Negotiation', year:2002, summary:'A systems approach that frees you from neediness.', ideas:['“No” is safe','Mission and purpose','Questions over assumptions'] },
  { id:'never-eat-alone', title:'Never Eat Alone', author:'Keith Ferrazzi', cat:'Communication', year:2005, summary:'Building a network through generosity, not transactions.', ideas:['Give before you ask','Ping constantly','Relationships compound'] },
  { id:'talking-to-strangers', title:'Talking to Strangers', author:'Malcolm Gladwell', cat:'Communication', year:2019, summary:'Why we misread people we don’t know.', ideas:['Default to truth','Transparency is a myth','Context matters'] },
  { id:'on-writing-well', title:'On Writing Well', author:'William Zinsser', cat:'Communication', year:1976, summary:'The classic guide to clear, simple nonfiction writing.', ideas:['Cut clutter','Write for the reader','Rewrite, rewrite'] },
  { id:'emotional-intelligence', title:'Emotional Intelligence', author:'Daniel Goleman', cat:'Psychology & Influence', year:1995, summary:'Why EQ can matter more than IQ.', ideas:['Self-awareness & regulation','Empathy','Social skill'] },
  { id:'quiet', title:'Quiet', author:'Susan Cain', cat:'Psychology & Influence', year:2012, summary:'The power of introverts in a world that can’t stop talking.', ideas:['Introvert strengths','Quiet leadership','Restorative niches'] },
  { id:'blink', title:'Blink', author:'Malcolm Gladwell', cat:'Psychology & Influence', year:2005, summary:'The power and pitfalls of split-second judgment.', ideas:['Thin-slicing','Trained intuition','Beware bias'] },
  { id:'switch', title:'Switch', author:'Chip & Dan Heath', cat:'Psychology & Influence', year:2010, summary:'How to change things when change is hard.', ideas:['Direct the Rider','Motivate the Elephant','Shape the Path'] },
  { id:'turn-the-ship-around', title:'Turn the Ship Around!', author:'L. David Marquet', cat:'Leadership', year:2012, summary:'Creating leaders at every level by giving control.', ideas:['Give intent, not orders','Competence + clarity','Leader-leader model'] },
  { id:'multipliers', title:'Multipliers', author:'Liz Wiseman', cat:'Leadership', year:2010, summary:'How the best leaders make everyone smarter.', ideas:['Multipliers vs diminishers','Ask great questions','Stretch your team'] },
  { id:'the-making-of-a-manager', title:'The Making of a Manager', author:'Julie Zhuo', cat:'Leadership', year:2019, summary:'A practical guide for new managers.', ideas:['Purpose, people, process','Feedback often','Manage yourself first'] },
  { id:'the-one-thing', title:'The One Thing', author:'Gary Keller & Jay Papasan', cat:'Habits & Productivity', year:2013, summary:'Extraordinary results by narrowing your focus.', ideas:['The focusing question','Time-block the one thing','Dominoes, not multitasking'] },
  { id:'indistractable', title:'Indistractable', author:'Nir Eyal', cat:'Habits & Productivity', year:2019, summary:'Master distraction and control your attention.', ideas:['Manage internal triggers','Make time for traction','Pact yourself'] },
  { id:'make-time', title:'Make Time', author:'Jake Knapp & John Zeratsky', cat:'Habits & Productivity', year:2018, summary:'Daily tactics to focus on what matters.', ideas:['Pick a Highlight','Beat distraction','Design your day'] },
  { id:'10-percent-happier', title:'10% Happier', author:'Dan Harris', cat:'Mindfulness & Wellbeing', year:2014, summary:'A skeptic’s guide to meditation that works.', ideas:['Tame the voice in your head','Meditation is a skill','Calm is trainable'] },
  { id:'breath', title:'Breath', author:'James Nestor', cat:'Mindfulness & Wellbeing', year:2020, summary:'The lost science of breathing and how to do it well.', ideas:['Breathe through the nose','Slow it down','Breathing shapes health'] },
  { id:'daring-greatly', title:'Daring Greatly', author:'Brené Brown', cat:'Relationships', year:2012, summary:'How vulnerability transforms how we live and connect.', ideas:['Vulnerability is courage','Shame resilience','Wholehearted living'] },
  { id:'the-four-agreements', title:'The Four Agreements', author:'Don Miguel Ruiz', cat:'Relationships', year:1997, summary:'A Toltec code for personal freedom.', ideas:['Be impeccable with your word','Don’t take things personally','Don’t assume; do your best'] },
  { id:'the-millionaire-next-door', title:'The Millionaire Next Door', author:'Thomas J. Stanley', cat:'Money & Business', year:1996, summary:'Surprising habits of America’s wealthy.', ideas:['Live below your means','Quiet wealth','Frugality compounds'] },
  { id:'the-e-myth-revisited', title:'The E-Myth Revisited', author:'Michael E. Gerber', cat:'Money & Business', year:1995, summary:'Why most small businesses fail and what to do.', ideas:['Work on, not in, the business','Systems run the business','Franchise your model'] },
  { id:'ego-is-the-enemy', title:'Ego Is the Enemy', author:'Ryan Holiday', cat:'Strategy & Philosophy', year:2016, summary:'How ego sabotages success and how to keep it in check.', ideas:['Stay a student','Humility over image','Detach from outcomes'] },
  { id:'letters-from-a-stoic', title:'Letters from a Stoic', author:'Seneca', cat:'Strategy & Philosophy', year:65, summary:'Seneca’s practical letters on living wisely.', ideas:['Time is your only wealth','Prepare for adversity','Philosophy as practice'] },
  { id:'the-tipping-point', title:'The Tipping Point', author:'Malcolm Gladwell', cat:'Psychology & Influence', year:2000, summary:'How little things create big social epidemics.', ideas:['Law of the few','Stickiness factor','Power of context'] },
];

if (typeof window !== 'undefined') window.KITHRA_BOOKS = KITHRA_BOOKS;
export { CATS };
export default KITHRA_BOOKS;
